name: GSI Build

on: [push]

env:
  ROM_URL: https://hugeota.d.miui.com/20.6.18/miui_MI6_20.6.18_3f5b90d469_9.0.zip
  ROM_NAME: miui
  ZIP_NAME: miui
  TZ: America/Sao_Paulo
  MIR: gof
  MIR2: trs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master


       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
 
       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/amyGSI/ErfanGSIs.git

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Execute Shell Script
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Copy and rename A-only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt
       
       - name: Upload A-Only GSI Images
         uses: actions/upload-artifact@v2
         with:
           name: Aonly-Image
           path: ErfanGSIs/output/*Aonly.7z
           if-no-files-found: error
       
       - name: Upload AB GSI Images
         uses: actions/upload-artifact@v2
         with:
           name: Aonly-Image
           path: ErfanGSIs/output/*AB.7z
           if-no-files-found: error
    

   
