name: GSI Build

on: [push]

env:
  ROM_URL: http://cdn-ota.blackshark.com/KLE-A0/20200807162741-klein-ota-signed_by_xiaomi_e806d3e500429fadac9deb16f309e70c.zip
  ROM_NAME: JoyUI
  ZIP_NAME: JoyUI
  TZ: America/Sao_Paulo
  MIR: wss
  MIR2: arp
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master


       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
 
       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/HitaloSama/ErfanGSIs.git

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Execute Shell Script
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Copy and rename A-only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt

       - name: Upload Aonly GSI Images
         uses: actions/upload-artifact@v2
         with:
           name: Aonly-Image
           path: ErfanGSIs/output/"$ZIP_NAME-Aonly-$sourcever2-$date2-ErfanGSI.7z"
           if-no-files-found: error

       - name: Upload AB GSI Images
         uses: actions/upload-artifact@v2
         with:
           name: Aonly-Image
           path: ErfanGSIs/output/"$ZIP_NAME-AB-$sourcever2-$date2-ErfanGSI.7z"
           if-no-files-found: error
    

   
